movieratings/app1/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from app1.views import MovieList, MostRatings, DetailRater, DetailMovie, \
    AvgRating, CreateRating, DeleteRating, UpdateRating

urlpatterns = [
    # url(r'list_movies/', 'app1.views.list_movies', name='list_movies'),
    url(r'^list_movies/', MovieList.as_view(), name='list_movies'),
    url(r'^most_ratings/', MostRatings.as_view(), name='most_ratings'),

    url(r'^user/(?P<rater_id>[0-9]+)/', DetailRater.as_view(),
        name='detail_rater'),

    url(r'^detail_movie/(?P<movie_id>[0-9]+)/', DetailMovie.as_view(),
        name='detail_movie'),

    url(r'^create_rating/(?P<movie_id>[0-9]+)/',
        login_required(CreateRating.as_view()), name='create_rating'),

    url(r'^delete_rating/(?P<rating_id>[0-9]+)/',
        login_required(DeleteRating.as_view()), name='delete_rating'),

    url(r'^update_rating/(?P<rating_id>[0-9]+)/',
        login_required(UpdateRating.as_view()), name='update_rating'),

    url(r'^avg_rating/', AvgRating.as_view(),
        name='avg_rating'),

    # url(r'^create_rating/(?P<movie_id>[0-9]+)/', 'app1.views.create_rating',
    #     name='create_rating'),

    # url(r'avg_rating/(?P<select_category>[A-z]+)', 'app1.views.avg_rating',
    #     name='avg_rating'),
    # url(r'most_ratings/', 'app1.views.most_ratings', name='most_ratings'),
    # url(r'detail_movie/(?P<movie_id>[0-9]+)/', 'app1.views.detail_movie',
    #     name="detail_movie"),
    # url(r'^user/(?P<rater_id>[0-9]+)/', 'app1.views.detail_rater',
    #     name="detail_rater"),
    # url(r'^change_rating/(?P<rating_id>[0-9]+)/', 'app1.views.change_rating',
    #     name="change_rating"),
    # url(r'^delete_rating/(?P<rating_id>[0-9]+)/', 'app1.views.delete_rating',
    #     name="delete_rating"),

 ]

movieratings/movieratings/ratings/ratings/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
]

movieratings/movieratings/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from app1.views import AccountProfile

urlpatterns = [
    url(r'^logout/', 'django.contrib.auth.views.logout',
        {'next_page':"/app1/list_movies"}, name='logout'),
    url('^', include('django.contrib.auth.urls')),
    url(r'^app1/', include('app1.urls')),
    url(r'^accounts/profile/', login_required(AccountProfile.as_view()),
        name='account_profile'),
    url(r'^admin/', include(admin.site.urls)),
]

movieratings/app1/models.py
import datetime
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import Avg


# Create your models here.
class Rater(models.Model):
    gender = models.CharField(max_length=1)
    age = models.IntegerField()
    occupation = models.IntegerField()
    zip_code = models.CharField(max_length=10)
    user = models.OneToOneField(User, null=True)

    def has_rated_movie(self, movie_id):
        rater = Rater.objects.get(pk=self.user.rater.id)
        ratings = rater.rating_set
        rated = len(ratings.filter(movie__id=movie_id)) > 0
        return rated

    def get_rating_list(self):
        return self.rating_set.all()

    def __str__(self):
        return 'id: {} gender: {} age: {} occupation: {} zip_code: {}'.\
            format(self.id, self.gender, self.age, self.occupation,
                   self.zip_code)


class Movie(models.Model):
    title = models.CharField(max_length=150)
    genre = models.CharField(max_length=150)

    def get_avg_rating(self):
        return self.rating_set.aggregate(Avg('ratings'))

    def get_user_list(self):
        return self.rating_set.all()

    def __str__(self):
        return 'title: {} genre: {}'.format(self.title, self.genre)


class Category(models.Model):
    category = models.CharField(max_length=150)
    movie = models.ManyToManyField(Movie)


class Rating(models.Model):
    rater = models.ForeignKey(Rater)
    movie = models.ForeignKey(Movie)
    ratings = models.IntegerField(validators=[MinValueValidator(1),
                                              MaxValueValidator(5)])
    timestamp = models.IntegerField(default=0)
    new_stamp = models.DateTimeField()

    @property
    def was_published_recently(self):
        now = datetime.timezone.now()
        return now - datetime.timedelta(days=1) <= self.timestamp <= now

    def __str__(self):
        return 'rater: {} movie: {} ratings: {} timestamp: {}'.\
            format(self.rater, self.movie, self.ratings, self.timestamp)

movieratings/app1/forms.py
from django.forms import ModelForm
from app1.models import Rating


class RatingForm(ModelForm):
    class Meta:
        model = Rating
        fields = ('ratings', )



# class UpdateRatingForm(ModelForm):
#     class Meta:
#         model = Rating
#         fields = ('ratings', )

movieratings/app1/views.py
import datetime
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse, reverse_lazy
from django.db.models import Avg, Count
from django.forms import Form
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render


# Create your views here.
from django.views.generic import ListView, DetailView, CreateView, DeleteView, \
    UpdateView
from app1.forms import RatingForm
from app1.models import Movie, Rater, Rating, Category


class MovieList(ListView):
    model = Movie
    template_name = "app1/list_movies.html"
    queryset = Movie.objects.all().order_by('title')
    paginate_by = 20


class MostRatings(ListView):
    model = Movie
    template_name = "app1/most_ratings.html"
    queryset = Movie.objects.exclude(rating=None).annotate(
        count=Count('rating__ratings')).order_by('-count')[:20]
    paginate_by = 10


class AccountProfile(ListView):
    model = Rating
    template_name = "app1/account_profile.html"
    paginate_by = 10

    def get_queryset(self):
        queryset = Rater.objects.get(
            pk=self.request.user.rater.id).get_rating_list()
        return queryset


class DetailRater(DetailView):
    model = Rater
    pk_url_kwarg = 'rater_id'
    template_name = 'app1/detail_rater.html'


class DetailMovie(DetailView):
    model = Movie
    pk_url_kwarg = 'movie_id'
    template_name = 'app1/detail_movie.html'

    def get_context_data(self, **kwargs):
        movie = self.object
        context = super(DetailMovie, self).get_context_data(**kwargs)
        context['rated'] = self.request.user.rater.has_rated_movie(movie.id)
        return context


class AvgRating(ListView):
    model = Movie
    template_name = "app1/avg_rating.html"
    paginate_by = 7

    def get_queryset(self):
        select_cat = self.request.GET.get("select_category", None)
        queryset = Movie.objects.exclude(rating=None)
        if select_cat != 'None':
            queryset = queryset.filter(
                category__category__icontains=select_cat)
        queryset = queryset.annotate(
            average=Avg('rating__ratings')).order_by('-average')[:20]

        return queryset

    def get_context_data(self, **kwargs):
        context = super(AvgRating, self).get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
        context['select_category'] = \
            self.request.GET.get("select_category", None)
        return context


@login_required(login_url='/login')
def change_rating(request, rating_id):

    if request.method == 'POST':
        form = RatingForm(request.POST)

        if form.is_valid():
            rating = Rating.objects.get(pk=rating_id)
            form_rating = form.save(commit=False)
            rating.movie_id = rating.movie.id
            rating.rater_id = request.user.rater.id
            rating.new_stamp = datetime.datetime.now()
            rating.ratings = form_rating.ratings
            rating.save()

            return HttpResponseRedirect(reverse('account_profile'))

    else:
        form = RatingForm()
    return render(request, 'app1/update_rating.html', {'form': form,
                                                       'rating_id': rating_id})


class UpdateRating(UpdateView):
    model = Rating
    fields = ['ratings']
    pk_url_kwarg = 'rating_id'
    template_name = "app1/update_rating.html"

    def get_success_url(self):
        return reverse('account_profile')


class DeleteRating(DeleteView):
    model = Rating
    pk_url_kwarg = 'rating_id'
    template_name = "app1/delete_rating.html"

    def get_success_url(self):
        return reverse('account_profile')


class CreateRating(CreateView):
    model = Rating
    fields = ('ratings',)
    success_url = reverse_lazy('detail_movie')
    template_name = "app1/create_rating.html"

    def get_success_url(self):
        return reverse('detail_movie',
                       kwargs={'movie_id': self.kwargs.get('movie_id', None)})

    def get_context_data(self, **kwargs):
        context = super(CreateRating, self).get_context_data(**kwargs)
        context['movie_id'] = self.kwargs.get('movie_id', None)
        return context

    def form_valid(self, form):
        form.instance.rater_id = self.request.user.rater.id
        form.instance.movie_id = self.kwargs.get('movie_id', None)
        form.instance.rating = form.cleaned_data.get('rating', None)
        form.instance.new_stamp = datetime.datetime.now()
        return super(CreateRating, self).form_valid(form)

movieratings/templates/app1/account_profile.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %}Profile{% endblock %}

{% block content %}
    {% csrf_token %}
    <h1>Hi, welcome to your user account:</h1>
    <h4><a href="{% url 'avg_rating' %}?select_category={{ 'None' }}">
        Click here for the top 20 rated movies
    </a></h4>
    <h4><a href="{% url 'most_ratings'  %}">
        Click here for the 20 most rated movies
    </a></h4>
    <h4><a href="{% url 'list_movies'  %}">
        Click here for ALL movies
    </a></h4><br>
        <h4>Here is a list of the movies that you have reviewed:</h4>
    {% for rating in rating_list %}
                <p class="tab">
                    <div class="alert-warning"> Movie: <b>{{ rating.movie.title }}</b></div>
                    You gave this movie a rating of:  {{ rating.ratings }}

        <style type="text/css">
        <!--
            .tab { margin-left: 40px; }
            .tab2 { margin-left: 80px; }
        -->
        </style>

            <p class="tab2">
                <a href="{% url 'update_rating' rating.id %}">
                    Change this rating</a><br>
                <a href="{% url 'delete_rating' rating.id %}">
                    Delete this rating</a>
            </p>

    {% endfor %}

{% endblock %}

movieratings/templates/app1/avg_rating.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %}List of Top 20 Rated Movies:{% endblock %}

{% block content %}
    {% csrf_token %}
    <h1>Here is the list of the top 20
        rated movies and their avg ratings.</h1>
        <div align="center">
            <b><a href="{% url 'list_movies' %}">
                List ALL movies:</a>
            </b>
        </div><br>
    <ol>
        {% if select_category != 'None' %}
            <h4>Filtered by Genre:<b>&nbsp;&nbsp;{{ select_category }}</b></h4>
        {% else %}
            <h4>Filter by Genre:</h4>
        {% endif %}

        {% for each in category_list %}
            <a href="{% url 'avg_rating' %}?select_category={{ each.category }}">
                &nbsp;{{ each.category }}&nbsp;|</a>
        {% endfor %}
        <a href="{% url 'avg_rating' %}?select_category={{ None }}">No Filter</a><br><br>
        {% for movie in movie_list %}
           <div class="alert-danger"><li>Movie:
           <a href="{% url 'detail_movie' movie.id %}">
                {{ movie.title }}</a></li></div>
                <p> Avg Rating:  {{ movie.average }}</p>
       {% endfor %}
    </ol>
    {% if is_paginated %}
    <p>
        {% if page_obj.has_previous %}
            <a href="{% url 'list_movies' %}?page={{ page_obj.previous_page_number }}"><< Prev</a>
        {% endif %}
        {{ page_obj }}
        {% if page_obj.has_next %}
            <a href="{% url 'list_movies' %}?page={{ page_obj.next_page_number }}">Next >></a>
        {% endif %}
    </p>
    {% endif %}

{% endblock %}

movieratings/templates/app1/category_page.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %}List of Top 20 Rated {{ select_category }}Movies:{% endblock %}

{% block content %}
    {% csrf_token %}
    <h1>Here is the list of the top 20 rated <br><b>{{ select_category }}</b>
        movies and their avg ratings.</h1>
    <ol>
        <h4>Filter by Genre:</h4>
        {% for each in category_list %}
            <a href="{% url 'category_page' each.category %}">
                &nbsp;{{ each.category }}&nbsp;|</a>
        {% endfor %}<br><br>
        {% for movie in avg_rating %}
           <div class="alert-danger"><li>Movie:
                <a href="{% url 'detail_movie' movie.id %}">
                     {{ movie.title }}
                </a></li>
           </div>
                <p> Avg Rating:  {{ movie.average }} </p>
       {% endfor %}
    </ol>

{% endblock %}

movieratings/templates/app1/change_rating.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %}Change Rating{% endblock %}

{% block content %}
    <h1>Please select the rating you would like to change to:</h1>
    <form method="post" action="{%  url 'change_rating' rating_id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit" value="Submit Change">
    </form>

{% endblock %}

movieratings/templates/app1/create_rating.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %}Create Your Rating:{% endblock %}

{% block content %}
    <h1>Create your Rating here:</h1>
    <form method="post" action="{%  url 'create_rating' movie_id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit" value="Submit Rating">
    </form>
{% endblock %}

movieratings/templates/app1/delete_rating.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %}Delete Rating{% endblock %}

{% block content %}
    <h3>Are you sure you want to delete your rating?</h3>
    <form method="post" action="{%  url 'delete_rating' rating.id %}">
        {% csrf_token %}
        <a href="{% url "account_profile" %}">No, cancel.</a>&nbsp;
        <input type="submit" name="delete" value="Delete Rating">
    </form>

{% endblock %}

movieratings/templates/app1/detail_movie.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %}Movie Details{% endblock %}

{% block content %}
    {% csrf_token %}
    <h1>Movie Detail</h1>
    <p><h3>Title:<b> {{ movie.title }}</b> </h3>
    <p>
        This movie has an Average Rating of:&nbsp;&nbsp;
        {{ movie.get_avg_rating.ratings__avg }}
    </p>
    {% if user.is_authenticated %}
        {% if not rated %}
            <a href="{% url 'create_rating' movie.id %}">
                Click here to rate this movie</a>

        {% endif %}
    {% else %}
        <a href="{% url 'create_rating' movie.id %}">
            Click here to login and rate this movie</a>
    {% endif %}
    <br>
    <h4>List of users who have rated this movie:</h4>
    <ul>
        {% for movie in movie.rating_set.all %}
            <li>
                <p>
                 <a href="{% url 'detail_rater' movie.rater_id %}">
                  Rater Id: {{ movie.rater_id }}</a>&nbsp;&nbsp;&nbsp;&nbsp;
                  Rating:  {{ movie.ratings }}&nbsp;&nbsp;&nbsp;&nbsp;
                    {% if movie.new_stamp != null %}
                        Rating date/time:  {{ movie.new_stamp }}
                    {% endif %}
                </p>
            </li>

        {% endfor %}

    </ul>
{% endblock %}

movieratings/templates/app1/detail_rater.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %}Detailed Rater Info:{% endblock %}

{% block content %}
    <h1>Rater Detail</h1>
    <p>ID: {{ rater.id }}</p>
    <p>Gender: {{ rater.gender }}</p>
    <p>Age: {{ rater.age }}</p>
    <p>Occupation: {{ rater.occupation }}</p>
    <p>Zip code: {{ rater.zip_code }} </p>
    <h3>All the movies rated by this user:</h3>
    {% for rating in rater.rating_set.all %}
            <li>
                <p>
                    Movie:
                        <a href="{% url 'detail_movie' rating.movie_id %}">
                            {{ rating.movie.title }}</a>
                                &nbsp&nbsp
                    Rating:  {{ rating.ratings }}
                </p>
            </li>
    {% endfor %}
{% endblock %}

movieratings/templates/app1/list_movies.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %}List of All Movies:{% endblock %}

{% block content %}
    {% csrf_token %}
    <h1>Here is the list of ALL Movies</h1>
    <h4 align="center"><a href="{% url 'avg_rating' %}?select_category={{ 'None' }}">
        Click here to see the top 20 highest rated movies
    </a></h4>
    <h4 align="center"><a href="{% url 'most_ratings'  %}">
        Click here to see the top 20 most rated movies
    </a></h4>
    <ul>

       {% for movie in movie_list %}
            <li><a href="{% url 'detail_movie' movie.id %}">{{ movie.title }}</a></li>

       {% endfor %}
    </ul>
    {% if is_paginated %}
    <p>
        {% if page_obj.has_previous %}
            <a href="{% url 'list_movies' %}?page={{ page_obj.previous_page_number }}"><< Prev</a>
        {% endif %}
        {{ page_obj }}
        {% if page_obj.has_next %}
            <a href="{% url 'list_movies' %}?page={{ page_obj.next_page_number }}">Next >></a>
        {% endif %}
    </p>
    {% endif %}
{% endblock %}

movieratings/templates/app1/most_ratings.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %}List of Most Rated Movies:{% endblock %}

{% block content %}
    {% csrf_token %}
    <h1>Here is the list of the 20 most rated movies:</h1>
        <div align="center">
            <b><a href="{% url 'list_movies' %}">
                Go back to the full list</a>
            </b>
        </div><br>
    <ul>
        {% for movie in movie_list %}
           <li><div class="alert-danger">Movie:
           <a href="{% url 'detail_movie' movie.id %}">
                {{ movie.title }}</a></div>

                There are {{ movie.count }} users who have rated this movie:
           </li>
       {% endfor %}
    </ul>
    {% if is_paginated %}
    <p>
        {% if page_obj.has_previous %}
            <a href="{% url 'most_ratings' %}?page=
                {{ page_obj.previous_page_number }}"><< Prev</a>
        {% endif %}
        {{ page_obj }}
        {% if page_obj.has_next %}
            <a href="{% url 'most_ratings' %}?page=
                {{ page_obj.next_page_number }}">Next >></a>
        {% endif %}
    </p>
    {% endif %}

{% endblock %}

movieratings/templates/app1/update_rating.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %}Change Rating{% endblock %}

{% block content %}
    <h1>Please select the rating you would like to change to:</h1>
    <form method="post" action="{%  url 'update_rating' rating.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit" value="Submit Change">
    </form>

{% endblock %}